Refactor to device
P8-Team/App pull request #48
Opened 2022-04-26 08:11 UTC by Kaliahh

2022-04-26 09:41 UTC, dkalaxdk approved these changes

2022-04-26 09:43 UTC, dkalaxdk approved these changes

2022-04-27 06:45 UTC, dkalaxdk approved these changes

2022-04-27 07:09 UTC, LauJosefsen requested changes
Kun lige ift identifier type ellers lgtm

2022-04-27 07:09 UTC, LauJosefsen commented on src/device/device.py
> +    def set_position(self, new_position):
Evt beskyt self.position hvis denne metode altid skal bruges

2022-04-27 07:34 UTC, dkalaxdk commented on test/test_end_to_end/test_input_to_output.py
> -    #                                          rounding=True)
Evt slet?

2022-04-27 07:34 UTC, dkalaxdk commented on test/test_end_to_end/test_input_to_output.py
> +            # calculate_position(result[i], do_draw=True)
Evt slet.

2022-04-27 07:34 UTC, dkalaxdk commented on test/test_end_to_end/test_input_to_output.py
> +            print(result[i].position, points[i])
Prints nødvændige?

2022-04-27 07:35 UTC, LauJosefsen approved these changes

2022-04-27 11:56 UTC, merged

2022-04-27 11:57 UTC, dkalaxdk approved these changes