Refactor to use config file
P8-Team/App pull request #58
Opened 2022-05-16 13:02 UTC by Kaliahh

2022-05-17 07:25 UTC, LauJosefsen requested changes

2022-05-17 07:25 UTC, LauJosefsen commented on src/frame_aggregator.py
> +    # TODO: Maybe add these to config?
enten fjern todo eller lav den? :D

2022-05-17 07:25 UTC, LauJosefsen commented on src/location/multi_lateration_non_linear_least_square_sum.py
> +        if math.isclose(self.distance, 0, abs_tol=1e-10) or math.isclose(self.variance, 0, abs_tol=1e-10):
Hvorfor er det ændret?

2022-05-18 11:09 UTC, soenderby commented on src/classifier.py
> +        self.hard_data_file = config['hard_data_file']
Jeg vil meget gerne have et bedre navn. 
Hard data means nothing

2022-05-18 11:10 UTC, soenderby approved these changes

2022-05-18 11:19 UTC, merged